<template>
  <NuxtLayout>
    <CaseStudy
      :pdf-url="'/pdf/blablacar-case-study.pdf'"
      :next-project-url="'/topchoice'"
      :prototype-url="'/blablacar/prototype'"
    />
  </NuxtLayout>
</template>
