<template>
  <NuxtLayout>
    <CaseStudy
      :pdf-url="'/pdf/top-choice-case-study.pdf'"
      :next-project-url="'/blablacar'"
      :prototype-url="'/topchoice/prototype'"
    />
  </NuxtLayout>
</template>
